### ISSUE TITLE
ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by dustinTopcoder** [topcoderinc/va-online-memorial-data-models#3]
When attempting to run, the following error is displayed:
>018-09-05T16:56:29.74-0500 [APP/PROC/WEB/0] ERR Wed, 05 Sep 2018 21:56:29 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/va-online-memorial-data-models/src/Notification.js:19
   2018-09-05T16:56:30.01-0500 [API/0] OUT Process has crashed with type: "web"
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     values: _.values(NotificationStatus),
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR             ^
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR ReferenceError: _ is not defined
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at module.exports (/home/vcap/app/node_modules/va-online-memorial-data-models/src/Notification.js:19:13)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/app/node_modules/va-online-memorial-data-models/index.js:44:51)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:652:30)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:663:10)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Module.load (module.js:565:32)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:505:12)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:497:3)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Module.require (module.js:596:17)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at require (internal/module.js:11:18)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/app/init-data.js:15:16)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:652:30)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:663:10)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Module.load (module.js:565:32)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:505:12)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:497:3)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at Function.Module.runMain (module.js:693:10)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at startup (bootstrap_node.js:191:16)
   2018-09-05T16:56:29.81-0500 [APP/PROC/WEB/0] ERR     at bootstrap_node.js:612:3
   2018-09-05T16:56:29.82-0500 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
   2018-09-05T16:56:29.82-0500 [APP/PROC/WEB/0] ERR npm ERR! errno 1
   2018-09-05T16:56:29.82-0500 [APP/PROC/WEB/0] ERR npm ERR! @va/rest-api@0.0.1 init-data: `node init-data.js`
   2018-09-05T16:56:29.82-0500 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
   2018-09-05T16:56:29.82-0500 [APP/PROC/WEB/0] ERR npm ERR!
   2018-09-05T16:56:29.82-0500 [APP/PROC/WEB/0] ERR npm ERR! Failed at the @va/rest-api@0.0.1 init-data script.
   2018-09-05T16:56:29.82-0500 [APP/PROC/WEB/0] ERR npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
   2018-09-05T16:56:29.83-0500 [APP/PROC/WEB/0] ERR npm ERR! A complete log of this run can be found in:
   2018-09-05T16:56:29.83-0500 [APP/PROC/WEB/0] ERR npm ERR!     /home/vcap/app/.npm/_logs/2018-09-05T21_56_29_828Z-debug.log

Link to code line below:
https://github.com/topcoderinc/va-online-memorial-data-models/blob/996614b64f434e163409127450ceddc56bb5684e/src/Notification.js#L19

**Comment by dustinTopcoder** [comment]
@jiangliwu, can you take a look at this?  This is happening after the last merge.

cc: @ksmacleod99

**Comment by jiangliwu** [comment]
@dustinTopcoder my problem, new MR pushed, https://github.com/topcoderinc/va-online-memorial-data-models/pull/4

**Comment by dustinTopcoder** [comment]
This one seems fixed now.  Thank you!
