### ISSUE TITLE
Error in sequelize when deploying

### ISSUE THREAD

**Issue by dustinTopcoder** [topcoderinc/va-online-memorial-data-models#5]
When deploying, I get the following error:

> 2018-09-05T20:59:50.41-0500 [APP/PROC/WEB/0] ERR Thu, 06 Sep 2018 01:59:50 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/va-online-memorial-data-models/node_modules/sequelize/lib/sequelize.js:242:13

I tried to disable the warning with the following code:
https://github.com/topcoderinc/va-online-memorial-data-models/blob/9deae4f88e6962911c9029e88d62f9a0d9c9b577/index.js#L17

However, the app still crashes with no error.  I suspect the config option is just depressing the error, but the problem is deeper than that.

**Comment by dustinTopcoder** [comment]
@jiangliwu, here's another I'm seeing while trying to deploy.  Can you take a look and see if it's related to the recent updates? 

cc: @ksmacleod99

**Comment by jiangliwu** [comment]
@dustinTopcoder i tried on local, this is a deprecated message(it always exist for backend), and it will never caused crashes, do you have any details log?

**Comment by dustinTopcoder** [comment]
Here's the full log: 

>2018-09-05T21:12:48.79-0500 [CELL/0] OUT Cell dd6f432d-8d2d-456e-b9fb-38da759216ce creating container for instance a3d396fa-a914-480d-57ff-b444
   2018-09-05T21:12:49.14-0500 [CELL/0] OUT Cell dd6f432d-8d2d-456e-b9fb-38da759216ce successfully created container for instance a3d396fa-a914-480d-57ff-b444
   2018-09-05T21:12:50.57-0500 [CELL/0] OUT Starting health monitoring of container
   2018-09-05T21:12:51.08-0500 [APP/PROC/WEB/0] OUT > @va/rest-api@0.0.1 init-data /home/vcap/app
   2018-09-05T21:12:51.08-0500 [APP/PROC/WEB/0] OUT > node init-data.js
   2018-09-05T21:12:51.46-0500 [APP/PROC/WEB/0] ERR Thu, 06 Sep 2018 02:12:51 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/va-online-memorial-data-models/node_modules/sequelize/lib/sequelize.js:242:13
   2018-09-05T21:12:53.23-0500 [APP/PROC/WEB/0] OUT [2018-09-06T02:12:53.238Z][INFO] success!
   2018-09-05T21:12:53.25-0500 [APP/PROC/WEB/0] OUT Exit status 0
   2018-09-05T21:12:53.37-0500 [API/0] OUT Process has crashed with type: "web"
   2018-09-05T21:12:53.39-0500 [API/0] OUT App instance exited with guid fbec4db9-11e0-486d-9100-270b082de178 payload: {"instance"=>"a3d396fa-a914-480d-57ff-b444", "index"=>0, "cell_id"=>"dd6f432d-8d2d-456e-b9fb-38da759216ce", "reason"=>"CRASHED", "exit_description"=>"Codependent step exited", "crash_count"=>8, "crash_timestamp"=>1536199973339968967, "version"=>"1986cf22-fc73-413f-b74d-264f767e7e3e"}
   2018-09-05T21:12:53.25-0500 [CELL/SSHD/0] OUT Exit status 0
   2018-09-05T21:12:53.34-0500 [CELL/0] OUT Cell dd6f432d-8d2d-456e-b9fb-38da759216ce stopping instance a3d396fa-a914-480d-57ff-b444
   2018-09-05T21:12:53.34-0500 [CELL/0] OUT Cell dd6f432d-8d2d-456e-b9fb-38da759216ce destroying container for instance a3d396fa-a914-480d-57ff-b444
   2018-09-05T21:12:54.19-0500 [CELL/0] OUT Cell dd6f432d-8d2d-456e-b9fb-38da759216ce successfully destroyed container for instance a3d396fa-a914-480d-57ff-b444

This is running on CloudFoundry which is much like Heroku.  Could you try a quick Heroku deployment and see if it gets the same error or a better log?  I can as well, but it will be tomorrow before I get a chance.

**Comment by jiangliwu** [comment]
@dustinTopcoder worked in heroku https://vaonline-b.herokuapp.com

> git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v heroku refs/heads/prototype:refs/heads/master 
Pushing to https://git.heroku.com/vaonline-b.git
POST git-receive-pack (191 bytes)
remote: Compressing source files... done.        
remote: Building source:        
remote: 
remote: -----> Node.js app detected        
remote: 
remote: -----> Creating runtime environment        
remote:                
remote:        NPM_CONFIG_LOGLEVEL=error        
remote:        NODE_VERBOSE=false        
remote:        NODE_ENV=production        
remote:        NODE_MODULES_CACHE=true        
remote: 
remote: -----> Installing binaries        
remote:        engines.node (package.json):  8.11.2        
remote:        engines.npm (package.json):   unspecified (use default)        
remote:                
remote:        Resolving node version 8.11.2...        
remote:        Downloading and installing node 8.11.2...        
remote:        Using default npm version: 5.6.0        
remote: 
remote: -----> Restoring cache        
remote:        Skipping cache restore (not-found)        
remote: 
remote: -----> Building dependencies        
remote:        Installing node modules (package.json)        
remote:        added 420 packages in 13.772s        
remote: 
remote: -----> Caching build        
remote:        Clearing previous node cache        
remote:        Saving 2 cacheDirectories (default):        
remote:        - node_modules        
remote:        - bower_components (nothing to cache)        
remote: 
remote: -----> Pruning devDependencies        
remote:        Skipping because npm 5.6.0 sometimes fails when running 'npm prune' due to a known issue        
remote:        https://github.com/npm/npm/issues/19356        
remote:                
remote:        You can silence this warning by updating to at least npm 5.7.1 in your package.json        
remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version        
remote: 
remote: -----> Build succeeded!        
remote: -----> Discovering process types        
remote:        Procfile declares types -> web        
remote: 
remote: -----> Compressing...        
remote:        Done: 79.1M        
remote: -----> Launching...        
remote:        Released v4        
remote:        https://vaonline-b.herokuapp.com/ deployed to Heroku        
remote: 
remote: Verifying deploy... done.
